spring:
  ai:
    vertex:
      ai:
        gemini:
          # Use kebab-case for the property name
          project-id: gen-lang-client-0490903100
          location: us-east4
          chat:
            options:
              # Ensure this model name is correct and available in us-east4
              model: gemini-2.5-pro-exp-03-25 # Example: Use a generally available model, or verify yours
              temperature: 0.7

  application:
    # 应用程序名称，用于标识此应用
    name: mindmingle

  # 允许循环引用（作为备选方案）
  main:
    allow-circular-references: true

  thymeleaf:
    # 关闭Thymeleaf模板缓存，开发环境下可以即时看到模板更改而无需重启应用
    cache: false

  datasource:
    # 数据库连接URL，指定连接到本地PostgreSQL服务器上的mindmingle数据库
    url: jdbc:postgresql://mindmingle5703.postgres.database.azure.com:5432/postgres
    # 数据库用户名
    username: mindmingle
    # 数据库密码 - 实际使用时应考虑加密或使用环境变量
    password: mm123456!
    # PostgreSQL数据库驱动类名
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 数据库模式自动更新策略：
      # update - 根据实体类自动更新数据库结构，但不会删除已有数据或表
      # 其他可选值: create, create-drop, validate, none
      ddl-auto: update

    properties:
      hibernate:
        # 设置Hibernate使用的SQL方言，确保生成的SQL语句符合PostgreSQL语法规范
        dialect: org.hibernate.dialect.PostgreSQLDialect

    # 是否在日志中显示Hibernate生成的SQL语句，便于调试
    show-sql: true

  cloud:
    azure:
      storage:
        blob:
          # 存储帐户的 Blob 服务端点 (从 Azure 门户复制)
          endpoint: https://mindminglefile.blob.core.windows.net/?sv=2024-11-04&ss=bfqt&srt=co&sp=rwdlacupiytfx&se=2025-05-09T21:19:18Z&st=2025-04-10T13:19:18Z&spr=https&sig=Sbcxxu5OkuQhfLp2wXdLrFlvHnfLpvTNSXhUHYHPFFU%3D
          # 如果你在本地运行且想连接真实 Azure, 确保本地环境有凭据
          # (例如，通过 Azure CLI 'az login' 登录, 或设置环境变量)

# 自定义属性，用于指定默认操作的容器名
azure:
  storage:
    container-name: generated-file

server:
  # 应用程序运行的HTTP端口
  port: 8080

logging:
  level:
#    com.azure.identity: DEBUG
    org:
      # Spring框架的日志级别设置为INFO，显示一般信息、警告和错误
      springframework: INFO
      hibernate:
        # 设置Hibernate SQL日志级别为DEBUG，会输出所有SQL语句
        SQL: DEBUG
        type:
          descriptor:
            # 设置为TRACE级别，可以显示SQL语句中的参数值，对调试非常有用
            sql: TRACE

# JWT配置
jwt:
  # JWT密钥 - 实际使用时应使用更复杂的密钥并通过环境变量注入
  secret: mindmingle_jwt_secret_key_for_authentication_and_authorization_2025
  # JWT令牌过期时间（秒）- 86400秒 = 24小时
  expiration: 86400

# OpenAI 配置
openai:
  api:
    # OpenAI API 密钥 - 实际使用时应通过环境变量注入
    key: ${OPENAI_API_KEY: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}
    # API 调用超时时间（秒）
    timeout: 60
    # 默认模型
    model: gpt-4o-mini

# Gemini API配置
gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro-exp-03-25:generateContent?key=${GEMINI_API_KEY:AIzaSyBwu6EuFKsUCF5iHUPxHZmABZyjd_0KYm0}




